CREATE TABLE `game_detail` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `game_id` int(11) DEFAULT NULL,
  `home_team` varchar(50) DEFAULT NULL,
  `guest_team` varchar(50) DEFAULT NULL,
  `game_time` datetime DEFAULT NULL,
  `avg_home_upoint` decimal(5,2) DEFAULT NULL,
  `avg_guest_upoint` decimal(5,2) DEFAULT NULL,
  `given_point` decimal(5,2) DEFAULT NULL,
  `bs_point` decimal(5,2) DEFAULT NULL,
  `home_lose` decimal(5,2) DEFAULT NULL,
  `home_wine` decimal(5,2) DEFAULT NULL,
  `given_point_home_lose` decimal(5,2) DEFAULT NULL,
  `given_point_home_wine` decimal(5,2) DEFAULT NULL,
  `big_point` decimal(5,2) DEFAULT NULL,
  `small_point` decimal(5,2) DEFAULT NULL,
  `point_diff_1_5_home_lose` decimal(5,2) DEFAULT NULL,
  `point_diff_6_10_home_lose` decimal(5,2) DEFAULT NULL,
  `point_diff_11_15_home_lose` decimal(5,2) DEFAULT NULL,
  `point_diff_16_20_home_lose` decimal(5,2) DEFAULT NULL,
  `point_diff_21_25_home_lose` decimal(5,2) DEFAULT NULL,
  `point_diff_26_home_lose` decimal(5,2) DEFAULT NULL,
  `point_diff_1_5_home_wine` decimal(5,2) DEFAULT NULL,
  `point_diff_6_10_home_wine` decimal(5,2) DEFAULT NULL,
  `point_diff_11_15_home_wine` decimal(5,2) DEFAULT NULL,
  `point_diff_16_20_home_wine` decimal(5,2) DEFAULT NULL,
  `point_diff_21_25_home_wine` decimal(5,2) DEFAULT NULL,
  `point_diff_26_home_wine` decimal(5,2) DEFAULT NULL,
  `created_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `update_ind` (`home_team`,`guest_team`,`game_time`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8;
